// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neon_vault.Data;

#nullable disable

namespace Neon_vault.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neon_vault.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Neon_vault.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
                            CoverImageUrl = "/images/game_card_1.png",
                            Description = "Dive into a sprawling cyberpunk metropolis as a rogue hacker with mysterious powers. Uncover corporate conspiracies, upgrade your neural implants, and shape the fate of Neo Shanghai in this award-winning open-world RPG.",
                            Developer = "NeonForge Studios",
                            Genre = "RPG",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neon Phantom"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567802"),
                            CoverImageUrl = "/images/game_card_2.png",
                            Description = "Fast-paced multiplayer FPS set on abandoned space stations. Team up with friends or go solo in intense 60-player battles across zero-gravity arenas. Features advanced movement mechanics and destructible environments.",
                            Developer = "Void Interactive",
                            Genre = "FPS",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Void Runners"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567803"),
                            CoverImageUrl = "/images/game_card_3.png",
                            Description = "A breathtaking fantasy adventure through shattered realms where magic and technology collide. Master elemental powers, solve ancient puzzles, and battle mythical creatures in a world teetering on the edge of destruction.",
                            Developer = "Rift Games",
                            Genre = "Adventure",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Arcane Rift"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567804"),
                            CoverImageUrl = "/images/game_card_4.png",
                            Description = "Lead an elite black-ops unit through 20 covert missions across the globe. Plan your approach, utilize stealth or go loud, and manage your squad's unique abilities in this tactical stealth-action thriller.",
                            Developer = "Shadow Works",
                            Genre = "Stealth",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shadow Ops"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567805"),
                            CoverImageUrl = "/images/game_card_5.png",
                            Description = "Descend into procedurally generated dungeons filled with relentless enemies and legendary loot. This hardcore action-RPG challenges you to master tight combat mechanics and build unstoppable character synergies.",
                            Developer = "Abyss Studios",
                            Genre = "Action RPG",
                            Price = 44.99m,
                            ReleaseDate = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark Descent"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567806"),
                            CoverImageUrl = "/images/game_card_6.png",
                            Description = "Hit the neon-lit streets in the ultimate arcade racing experience. Customize 50+ licensed vehicles, drift through iconic city circuits, and compete in online championships with players worldwide.",
                            Developer = "Speed Studios",
                            Genre = "Racing",
                            Price = 34.99m,
                            ReleaseDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Turbo Drift X"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567807"),
                            CoverImageUrl = "/images/game_card_7.png",
                            Description = "Chart your course through an infinite procedurally generated galaxy. Mine asteroids, trade exotic goods, build space stations, and discover alien civilizations in this relaxing yet deep space exploration simulator.",
                            Developer = "Cosmos Labs",
                            Genre = "Exploration",
                            Price = 54.99m,
                            ReleaseDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stellar Voyage"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567808"),
                            CoverImageUrl = "/images/game_card_8.png",
                            Description = "Humanity's first contact with alien intelligence has gone wrong. As a military scientist, use experimental portal technology to hop between dimensions, solve reality-bending puzzles, and prevent a multiverse collapse.",
                            Developer = "Protocol Games",
                            Genre = "Sci-Fi",
                            Price = 24.99m,
                            ReleaseDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gate Protocol"
                        });
                });

            modelBuilder.Entity("Neon_vault.Models.LibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("LibraryItems");
                });

            modelBuilder.Entity("Neon_vault.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Neon_vault.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Neon_vault.Models.CartItem", b =>
                {
                    b.HasOne("Neon_vault.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Neon_vault.Models.LibraryItem", b =>
                {
                    b.HasOne("Neon_vault.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Neon_vault.Models.OrderItem", b =>
                {
                    b.HasOne("Neon_vault.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Neon_vault.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Neon_vault.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
